### ISSUE TITLE
Bulk prefetch tiles easily 

### ISSUE THREAD

**Issue by stoft** [otsaloma/poor-maps#34]
It would be great with a function that would allow me to download all tiles of  a location quickly without having to  zoom in on each tile. E.g. if I'm going on a trip I want to prefetch tiles of my destination city , but if it's a big city then I want to fetch them without having  to first  zoom in and then scroll through half the city.
One way of doing this could be using location name (download Berlin, Germany etc.). Another could be to do it for visible area of map or similar.

**Comment by otsaloma** [comment]
I fully understand the convenience factor, but currently due to the low user count we're still on free of charge plans with all service providers. They very clearly condemn bulk downloads of tiles, e.g.

> Bulk downloading is strongly discouraged. Do not download tiles unnecessarily.

http://wiki.openstreetmap.org/wiki/Tile_usage_policy

> Absolutely no bulk-downloading scraping, pre-downloading, pre-caching or anything similar. If you need the ability to do this, you’ll need prior written agreement and an appropriate service plan. Please see further details about Bulk Downloads, below.

https://www.thunderforest.com/terms/

Deviating from these rules would risk getting us a user-agent ban. And the providers that could perhaps allow it are subject to free plan limits, which would be quickly exceeded by bulk downloads.

So, this is a big no-no, until we either pay big money for a big plan or have our own tileserver, of which the latter (tracked as issue #33) seems more likely as commercial services are very expensive and it's difficult to cover the cost while there's no convenient way to charge for the app.

**Comment by stoft** [comment]
Ok, thank you, I was unaware of the underlying service policies, that makes perfect sense.
