### ISSUE TITLE
Arrangement of navigation informations, menu button and NorthArrow

### ISSUE THREAD

**Issue by denis-robel** [otsaloma/poor-maps#46]
Hallo,

when I'm using poor-maps in landscape mode with Jolla C the menu button is situated in the map center and the actual position will be covered by the menu button.
Maybe its better to put the menu button to the right and the NorthArrow on top of the menu button.
An in my opinion the information band for navigation is to big - reduce the hight of the whole band would be better. Here some suggestions:
1. direction picture is okay
2. put the narration distance directly under the direction picture, use little bit smaller font hight, so that the picture width and the distance width are the same
3. arrange navigation information and total distance on the same top position as the direction picture

with best regards 

Denis

p.s. It's a very great app, I love it

**Comment by otsaloma** [comment]
I moved the position auto-centering in #14. It seems I didn't check how it works in landscape. That can be fixed.

In general, pretty much everything in the UI is designed to best fit portrait use and I'm not going to make things worse for portrait. A different layout for landscape is possible, but I don't know if it's worth the trouble. Why are you using landscape anyway?

The menu button is in the center because the left corner is difficult for left-hand use and right corner difficult for right-hand use. In portrait mode center works well. And right-handed people sometimes use their phone with the left hand and vice versa, so adding handedness to the preferences screen is not a good idea.

**Comment by denis-robel** [comment]
okay I'm understanding the position of the menu button.
I'm using the landscape mode because of the phone holder and the angel of the front window of my car are no friends - I can mount my Jolla in landscape orientation only. 
Of course it makes more sense using portrait mode because you can look more forward on your course.
So maybe the position auto-centering should be ptimized for landscape mode only.
Thank you for your quick replay.

Denis
