### ISSUE TITLE
Navigation only uses the first possible result

### ISSUE THREAD

**Issue by Profpatsch** [otsaloma/poor-maps#5]
When I try to navigate to `Friedberg`, it automatically chooses the first (wrong) result from the results Nominatim provides (compare http://www.openstreetmap.org/search?query=friedberg#map=18/48.35461/10.98271&layers=T)

It should either:
1) Show a list of possible results first (like openstreetmap.org does)
or
1) Navigate to the result
2) Provide an easy way to select another result when the first one is the wrong one

**Comment by otsaloma** [comment]
This is by design. I didn't want too many steps as on a small screen as they'd really have to be separate full-screen steps.

What you can do is either
1. Specify the state, province (or whatever) as "Friedberg, State" so that you can expect the first result to be correct.
2. Choose Search instead of Navigate from the main menu. Select the correct Friedberg. On the map you should see a bubble with a route button. Hit that -- it will relay coordinates instead of the name to the router.

The second of these options is what the big boys (Google, Apple, HERE) seem to favor and provide it as the only alternative. You first find the place, then ask for directions to get there. I figured I'd provide many ways to do the same thing. I don't know if this is good.

> Provide an easy way to select another result when the first one is the wrong one

When hitting the menu button, you're always taken to the last viewed page. So it should already be possible to look through search results one by one.

**Comment by Profpatsch** [comment]
I see two usability problems:
1. It is not clear that there are more results
2. The user is not sure what he has to search for to get the right result

So yes, that’s probably why the big guys only use destination-driven routing (and display multiple results with the most probable one up top).

**Comment by otsaloma** [comment]
I probably should switch to that destination-driven routing, but I'll need to think about it a while longer.

I'll have to look through this overlong review again: https://designexplosions.academy/design-explosions-mapping-on-ios-ad4ec6ba5c59

**Comment by Profpatsch** [comment]
Wow, reading the article it’s amazing how much thought went into those apps.

**Comment by otsaloma** [comment]
I had a closer look at how Google and Apple do navigation, and it turns out that they as well offer a direct navigate screen with from and to fields. It's less prominent and probably less used, but does exist. The way they can avoid excessive screens and steps is that they do autocompletion for from and to right there on the same screen. Nominatim isn't really usable for autocompletion, so I can't do that. Mapzen Search, which is included in Poor, claims to be "built from the bottom up to support autocomplete", but is still too young to be relied on as the default.

So, I think I'll want to keep the navigation screen, but maybe fix it in time using auto-completion. Basically, the current screens that show query history could show auto-complete results. I'll keep this issue open, also apart from auto-complete, maybe some small things can be done to mitigate problems.

Golden Path #2: https://designexplosions.academy/design-explosions-mapping-on-ios-ad4ec6ba5c59#ee9b

**Comment by otsaloma** [comment]
> So, I think I'll want to keep the navigation screen, but maybe fix it in time using auto-completion.

With da0dcaf0bdcb96408acb2d315f632cc6afdb4b2f, all geocoders should now be capable of autocompletion. However, I'll wait for Poor Maps to be allowed in the Jolla Store (depends on Sailfish ported to Qt 5.6) before adding autocompletion in the UI, as I need to be able to estimate the request count and possible cost.
