### ISSUE TITLE
Enhance POI search (by "official" taglist?)

### ISSUE THREAD

**Issue by palbr** [otsaloma/poor-maps#59]
My use case: I wanted search next filling stations around my current position. (My car was low on gas)

In German the appropriate word would be "Tankstelle". This translates to the English words "filling station" or "gas station". (PoorMaps lists "Gas Station" as example POI search term)

But POI searches with both translations failed in PoorMap (+ OSM Scout Server), since the "official" tag name for this kind of infrastructure is "amenity : fuel". (http://wiki.openstreetmap.org/wiki/Map_Features)

Another example: Search for "drugstore" gives no results, since the "official" tag name is "pharmacy".

**Solution 1:**
In my opinion this problem could be solved by providing a list of "official" OSM tags in PoorMap's POI search dialog. (Advanced enhancement: This list of tags might have translatable descriptions and might have icons ;)
I am not sure, whether all those tags are needed. I can't imagine a use case, someone is searching for "barrier : fence".

**Solution 2:**
Another way to solve this problem would be to add some automatic mapping for the "most used" use cases. Search for "gas station" maps to search for "fuel". But I guess it would be quite difficult to identify those "most used" uses cases.

I personally don't like algorithms doing "magic stuff", so I would prefer solution 1.

**Comment by otsaloma** [comment]
OSM POI types have no special significance in a multi-provider client such as Poor Maps. And as OSM data is really bad for POIs (incomplete, outdated, provides no details), there's no point designing a system tied to that.

In my view, this is clearly a case to be handled by the provider servers, not the client. The server should have aliases, or "magic" as you call it. Your "gas station" example works in Nominatim, by the way, due to its [aliases](http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN). If you prefer to use OSM Scout Server, please ask for the problem to be fixed there.

Near duplicate: #54
